### ISSUE TITLE
Support for sort and filter?

### ISSUE THREAD

**Issue by mattsears18** [BowlingX/ra-postgraphile#41]
I'm trying to decide on a backend for a new admin portal app and my decision will be largely influenced by which one is easiest to integrate with react-admin. I'm open to using firestore or appsync if one of those proves to be easier to integrate with react-admin, but I already have data in a Postgres database, so I'm also considering postgraphile or postgrest. 

[This firestore data provider](https://github.com/benwinding/react-admin-firebase) supports sorting by columns out of the box, and I found it very easy to add filters. This would work perfectly for what I need, but I would need to migrate my db to firestore.

I tried out this [amplify data provider](https://github.com/MrHertal/react-admin-amplify) too but quickly found that sorting and filtering required quite a bit of work to set up.

Does ra-postgraphile support sorting by columns out of the box? What about filters? Is it pretty easy to set up sorting and filters with ra-postgraphile (similar to the firestore data provider above), or will it take a lot of work (similar to the amplify data provider above)?

**Comment by BowlingX** [comment]
Hi :)
Thank you for considering this project.

Sorting (no known limitations) and filtering is supported, although filters are currently a bit limited and not all data types are supported (supported currently text, exact and fuzzy matches, and boolean filters. A pull request to implement more types and custom filtering is currently open https://github.com/BowlingX/ra-postgraphile/pull/17 and work in progress.

Otherwise it follow the default `react-admin` filter and sorting implementations, so no extra work to seutp.
It depends on your database (e.g. available indices) what sorting and filtering options become available through your graphql schema.

**Comment by BowlingX** [comment]
You can see an example schema that we use in our tests here: https://github.com/BowlingX/ra-postgraphile/blob/master/migrations/committed/000001.sql
